#!/bin/bash

#
# NOTE: specify the absolutepath of the file to use for logging.
#       'stdout' and 'stderr' are valid values.
#

chunkc core::log_file stdout 

#
# NOTE: specify the desired level of logging.
#
#       - none, debug, warn, error
#

chunkc core::log_level error

#
# NOTE: specify the absolutepath to the directory to use when
#       loading a plugin. '~' expansion is supported.
#

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins

#
# NOTE: if enabled, chunkwm will monitor the specified plugin_dir
#       and automatically reload any '.so' file that is changed.
#

chunkc core::hotload 0

chunkc set global_desktop_mode           bsp

chunkc set global_desktop_offset_top     5
chunkc set global_desktop_offset_bottom  5
chunkc set global_desktop_offset_left    5
chunkc set global_desktop_offset_right   5
chunkc set global_desktop_offset_gap     10

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                0
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           off
chunkc set window_float_next             0
chunkc set window_region_locked          1

chunkc set mouse_modifier                fn

chunkc core::load tiling.so

#
# NOTE: shell commands require escaped quotes
#       to pass value containing a whitespace.
#

chunkc tiling::rule --owner Finder --name Copy --state float
chunkc tiling::rule --owner \"App Store\" --state float

chunkc tiling::rule --owner \"MySQLWorkbench\" --state float
chunkc tiling::rule --owner \"Instruments\" --state float
chunkc tiling::rule --owner \"App Store\" --state float
chunkc tiling::rule --owner \"Finder\" --state float
chunkc tiling::rule --owner \"System Preferences\" --state float
chunkc tiling::rule --owner \"Telegram\" --state float
chunkc tiling::rule --owner \"BetterZip\" --state float
chunkc tiling::rule --owner \"Terminal\" --state float
chunkc tiling::rule --owner \"Gimp\" --state float
chunkc tiling::rule --owner \"Ukelele\" --state float
chunkc tiling::rule --owner \"Screen Sharing\" --state float
chunkc tiling::rule --owner \"Activity Monitor\" --state float
chunkc tiling::rule --owner \"TextEdit\" --state float
chunkc tiling::rule --owner \"Calculator\" --state float
chunkc tiling::rule --owner \"iTerm2\" --state float

# PHPStorm rule
chunkc tiling::rule --owner \"PhpStorm\" --state float --except \".* - \[.*\"

# Android Studio
chunkc tiling::rule --owner \"Android Studio\" --state float --except \".* - \[.*\"
