#!/bin/bash

chunkc core::plugin_dir ~/.chunkwm_plugins
chunkc core::hotload 1

chunkc core::load tiling.so

chunkc set global_desktop_mode           bsp

chunkc set global_desktop_offset_top     10
chunkc set global_desktop_offset_bottom  10
chunkc set global_desktop_offset_left    10
chunkc set global_desktop_offset_right   10
chunkc set global_desktop_offset_gap     10

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set window_focus_cycle            monitor
chunkc set mouse_follows_focus           1
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1

#
# NOTE: shell commands require escaped quotes
#       to pass value containing a whitespace.
#
# chunkc set mouse_modifier              \"cmd shift\"
chunkc set mouse_modifier                fn

chunkc set window_float_topmost          0
chunkc set window_fade_inactive          0
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.5


# PhpStorm
# chunkc tiling::rule --owner PhpStorm --except==".*\[.*" --state float 

# Android Studio
# chunkc tiling::rule --owner \"Android Studio\" --state float

# Firefox
chunkc tiling::rule --owner \"Firefox.*\" --name \".*DownThemAll!.*\" --state float

# Global
chunkc tiling::rule --owner \"MySQLWorkbench\" --state float
chunkc tiling::rule --owner \"Instruments\" --state float
chunkc tiling::rule --owner \"iTerm2\" --state tile
chunkc tiling::rule --owner \"Terminal\" --state float
chunkc tiling::rule --owner \"App Store\" --state float
chunkc tiling::rule --owner \"Finder\" --state float
chunkc tiling::rule --owner \"System Preferences\" --state float
chunkc tiling::rule --owner \"Telegram\" --state float
chunkc tiling::rule --owner \"BetterZip\" --state float
chunkc tiling::rule --owner \"Terminal\" --state float
chunkc tiling::rule --owner \"Gimp\" --state float
chunkc tiling::rule --owner \"Ukelele\" --state float
chunkc tiling::rule --owner \"Screen Sharing\" --state float
chunkc tiling::rule --owner \"Activity Monitor\" --state float
chunkc tiling::rule --owner \"TextEdit\" --state float
chunkc tiling::rule --owner \"Calculette\" --state float
