#! /bin/sh

bspc config border_width        2
bspc config window_gap         10
bspc config top_padding        12
bspc config left_padding       0

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc monitor HDMI1 -d 1 2 3 4 5 
bspc monitor VGA1  -d 6 7 

# Rules
bspc rule -a Gimp desktop=^1 follow=on
bspc rule -a Firefox desktop=^2
bspc rule -a Spotify pseudo_tiled=on
bspc rule -a Nautilus pseudo_tiled=on
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a feh floating=on manage=off

bspc monitor -f primary

## autostart
xsetroot -cursor_name left_ptr
setxkbmap fr
wmname LG3D
xcompmgr -f -D2 &
feh --randomize --bg-scale ~/Images/OSX/* &
xset -b
# compton -cCGf --vsync opengl --shadow-exclude '!focused' &
#conky &
#run_once xfce4-power-manager &
#run_once gnome-screensaver &
~/.config/bspwm/panel &

