#!/bin/sh

source ~/.config/bspwm/panel.cfg

if [ $(pgrep -cx panel) -gt 1 ] ; then
	killall panel
	#printf "%s\n" "The panel is already running." >&2
	#exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

trayer --edge top --align right --widthtype pixel --width 50 --heighttype pixel --height $BARHEIGHT --tint 0x$BLACK --transparent true --alpha 0 &

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &

xtitle -sf 'T%s' > "$PANEL_FIFO" &
conky -c ~/.config/bspwm/panel_conky > "$PANEL_FIFO" &


#cat "$PANEL_FIFO" | ~/.config/bspwm/panel_bar | bar -g ${BARWIDTH}x${BARHEIGHT} -f "$PANEL_FONT_FAMILY" -F "$FOREGROUND" -B "$BACKGROUND" -u "$UNDERLINE_WIDTH" &
cat "$PANEL_FIFO" | ~/.config/bspwm/panel_bar | lemonbar -F "$FOREGROUND" -B "$BACKGROUND" -u "$UNDERLINE_WIDTH" -f "roboto mono:size=10" -f "FontAwesome:size=10" &

wait
