#! /bin/sh

bspc config border_width       1
bspc config window_gap         10
bspc config top_padding        15
bspc config left_padding       0

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc config click_to_focus true

bspc monitor -d 1 2 3 4
# bspc monitor VGA1  -d 5 6

# Rules
bspc rule -a Gimp desktop=^1
bspc rule -a Firefox desktop=^2
bspc rule -a Spotify pseudo_tiled=on
bspc rule -a Nautilus pseudo_tiled=on
bspc rule -a File-roller pseudo_tiled=on
bspc rule -a feh floating=on manage=off

bspc monitor -f primary

## autostart
xsetroot -cursor_name left_ptr
setxkbmap fr bepo
wmname LG3D
xcompmgr -f -D2 &
feh --randomize --bg-scale ~/Images/wallpapers/* &
xset -b
polybar valentin &
