# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias irssi='ssh server -t "tmux attach"'
alias tmux="~/Dropbox/Linux/dotfiles/tmux/tools/manage.sh"
alias passtype="PASSWORD_STORE_ENABLE_EXTENSIONS=true pass type -a"
alias apk="adb install -r"
alias logcat="adb logcat"
alias todaystory="git log --pretty=format:'- %s' --after='yesterday'"
alias yesterdaystory="git log --pretty=format:'- %s' --since=yesterday --before=0am"

function serve() {
  echo "Scan open port 8888…8899"
  for (( PORTNUMBER = 8888; PORTNUMBER < 8899; PORTNUMBER++ )); do
    # Test si port dispo
    PDISPO=`ss -an | grep $PORTNUMBER | grep -i listen | wc -l | awk '{print $1}'`
    if [ $PDISPO -eq 0 ]
      then
        echo "Open port found : $PORTNUMBER"
        python3 -m http.server $PORTNUMBER
        break
    fi
  done
}

function killp(){
    if [ "$1" != "" ]
    then
			kill $(lsof -ti :$1 -sTCP:LISTEN) || echo "No process found for port 3000"
    else
    	echo "Please specify a port killp 3000"
    fi
}

function workon(){
	source ~/venv/$1/bin/activate
}

export SSH_AUTH_SOCK="$HOME/.gnupg/S.gpg-agent.ssh"
export VISUAL=vim
export EDITOR="$VISUAL"

if [[ `uname` == 'Darwin' ]]
then
	alias fastpass="openssl rand -base64 32 | pbcopy - && echo 'The generated password is in your clipboard'"
	alias ss="netstat"
	export ANDROID_HOME=$HOME/Library/Android/sdk/
	export JAVA_HOME="/Applications/Android Studio.app/Contents/jre/JDK/Contents/Home/"
	export PATH=${PATH}:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools

	export PATH="$PATH:$HOME/.composer/vendor/bin"

	export PATH="/usr/local/opt/python@2/bin:$PATH"
	. /usr/local/etc/profile.d/z.sh
fi

# Fix alt + {left, right} ENFIN !
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word
